spring.autoconfigure.exclude[0]=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
spring.autoconfigure.exclude[2]=org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration
spring.datasource.url= none
spring.datasource.username=none
spring.datasource.password=none


spring.activemq.broker-url= none
queue.trainerWorkload=trainerWorkloads.queue


spring.docker.compose.enabled=false

# JWT configuration
jwt.secret=onlyageniuscouldloveawomanlikeme
jwt.lifetime=60m

eureka.client.enabled=false
